config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index' 
  get 'contact' , to: 'welcome#contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersonalBlog</title>
    <%= csrf_meta_tags %>

   
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/contact.html.erb
<html>
<title>	Contact Me!</title>
<head ><h1><i><p align="center">Email: bhantanasmit@gmail.com</p></i></h1></head>
<%= link_to 'Home',root_path %>
<body bgcolor="#7C4DFF">
</body>
</html>

app/views/welcome/index.html.erb
<html>
<title>	Asmit Bhantana </title>
<head ><h1><i><p align="center">Welcome to my Personnel Profelio!</p></i></h1></head>
<br />
<body bgcolor="#7C4DFF">
<hr align="left" width="100%"/>
	
	<h3><p align="center" >Brief About Me!</p></h3>
	<hr align="left" width="100%"/>
	<br />
	<h4><p align="center" >I am Computer Engineering student. I love to code and make new things for benifit of people. I started to code since I was on Highschool. Since then I have learned many things about programming. I love to share my understanding although it's little with my friends and anyone interested as it give me some oppturnity to help me understand more. I first taught myself some Java and since then I have learnt following languages: </p></h4>
	<ol class="center">
		<li>C</li>
		<li>Java</li>
		<li>Python</li>
		<li>Ruby</li>
		<li>Fortan</li>
	</ol>
	<hr align="left" width="100%"/>
	<h2><p align="center" >Follow Me On Social:</p></h2>
	<ul class="center">
		<li><a href="https://www.facebook.com/asmit.bhantana.92?ref=bookmarks">Facebook</li>
		<li><a href="https://plus.google.com/106861500057064746629">Google+</li>
		<li><a href="https://twitter.com/bhantana_asmit">Twitter</li>
		<li><a href="https://www.youtube.com/channel/UCVDKIYoY6_fQnYKQrIMfL7g">Youtube</li>
		<li><a href="https://www.instagram.com/bhantanaasmit/">Instagram</li>
	</ul>
	
	</body>
<style type="text/css">
 .center { text-align: center; list-style-position:outside;}
</style>
<%= link_to 'Contact',contact_path %>
</html>